name: Trigger Dotcom Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master
    paths:
      - 'results/**'

jobs:
  redeploy-dotcom:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Trigger redeploy
        run: railway redeploy --service ${{ secrets.DOTCOM_RAILWAY_SERVICE_ID }} --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.DOTCOM_RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.DOTCOM_RAILWAY_PROJECT_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.DOTCOM_RAILWAY_ENVIRONMENT_ID }}
